### ISSUE TITLE
Installing Apps

### ISSUE THREAD

**Issue by chiaravalle** [lubomyr/uae4arm#44]
Hello everyone.
I'm trying to install some Apps I got from Aminet, in .lha format.
So far, I tried to extract it in the Amiga filesystem, but then I can't browse the folder from WorkBench.
What else should I try?

Thanks for any help.

**Comment by mike111769** [comment]
Are you using a directory or img file?

If directory, I just have a folder called "unzip" mounted as an HDD, and use android to uninstall to that directory..

If your looking for the actual install location it should ask/show on install start.

**Comment by chiaravalle** [comment]
I run WorkBench from a directory, then I made a \App subdirectory, in which I uncompressed the file.
Should I rather boot from a separate extract folder?

**Comment by mike111769** [comment]
It's up to you, for me it's just easier to click the unzip HDD icon on the workbench screen.. then install whatever I uncompressed there. plus I have a backup there.

Also don't forget in the open window, if you do use android to uncompress anything right click on the open window go to the top of screen to window drop down and show all, otherwise the files will be hidden...

**Comment by mike111769** [comment]
Your welcome.

Well that's why I brought up the Android unzip, any decent file manager will do it, and you don't even need it in the Amiga environment unless your going for the full experience.

To me Emulators are the combination of the best of both worlds....

As for the hidden files, when you write a file to storage, it makes an .info file with the actual file separate , it has icon Pic info, and file attribute information, that's why you can't see the when written outside the workbench environment.

**Comment by chiaravalle** [comment]
I see, that was what I missed.
New layout:
I have a folder named App, which I mount as DH1.
I uncompress the archives with a Android App, named "LHA For Android", in the local FileSystem. Then copy extract folder to MicroSD in the App folder.
